allowBuilds:
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
overrides:
  brace-expansion@1: ">=1.1.12 <2.0.0"
  brace-expansion@2: ">=2.1.2 <3.0.0"
  brace-expansion@5: ">=5.0.7 <6.0.0"
  "@keystatic/core>js-yaml": ">=4.3.0"
